### ISSUE TITLE
Fuck you

### ISSUE THREAD

**Issue by fulldecent** [IntelligenceX/ip2tor#1]
That is all

**Comment by maximlomans** [comment]
what kind of a cunt would open an issue just to insult someone, here, not on fb ?
 i dont get it; i thought this sort of thing didn't happen on github - this guy gets a 'pro' tag and deduces impunity from it ..did he steal his idea of tor ip blacklist ? fork it, not to his liking ? girlfriend bit his dick off and had nowhere else to go but github, to squeal ? 
wtf 
mind yous, i cussed all week .. loop busted my funds and my colgioni

**Comment by fulldecent** [comment]
Anybody can get a pro tag, that does not make me special. If you want to support GitHub and maybe get some features, maybe check it out.

The `ip2tor` project exists to help websites that block Tor users. And this issue expresses the sentiment of the many users downstream, whether because they are in repressed countries, they like liberty, or they like security/privacy, use Tor.

In the year 2021 when Google and Facebook employees will quit their livelihood and put their careers as risk to protest how their employers are hurting people, you can also expect open source projects that are anti-human, like this one, to receive strong negative feedback.

---

And thank you for reading closed issues.

**Comment by maximlomans** [comment]
ok,
 so you took a stand, but how was i, or anyone, supposed to know what your beef is with 'ip2tor's developer' ? - still, lightning nodes make use of ip2tor, checking on exit nodes , hops, fees, etc. that is how i ended up here - i mean you could have elaborated on it straight away, as you just did in your reply.. (i understand you a little better now) the cussing doesn't shock me, the vagueness and impulsivity of it, here, did.
i must add i didn't expect you to reply, i thought it was the developer ...
 ..but i'm glad you did - 
i guess now the developer does so too, understands your point of view .

i read closed issues all the time, the first place i look is under closed, which typically means 'solved' .. i rather check first, than open a new issue and not get any replies anyways,  plus I rather fix my own issues, might have something to do with pride .

**Comment by maximlomans** [comment]
│ To enable easy reachability with normal browser from the outside  │
                          │ consider adding a IP2TOR Bridge (MAINMENU > SUBSCRIBE)
b.t.w 
vulns on exit nodes - researcher link 
https://www.makeuseof.com/tag/priority-wretched-hive-scum-villainy-5-ways-stay-safe-bad-tor-exit-nodes/
